# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute
admin_routes:
    resource: routes/admin.yaml
    type: yaml

public_routes:
    resource: routes/public.yaml
    type: yaml
