vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
    mappings:
        product:
            uri_prefix: /uploads/images/product
            upload_destination: "%kernel.project_dir%/public/uploads/images/product"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
